# Generated by Django 5.0.4 on 2024-04-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_bloguser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
